# Generated by Django 6.0.4 on 2026-04-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsection',
            name='cor_bloco',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cor_fundo',
            field=models.CharField(default='#f8f9fa', max_length=7),
        ),
    ]
