# Generated by Django 6.0.4 on 2026-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contentsection_cor_bloco_portfolio_cor_fundo'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
