# Generated by Django 6.0.4 on 2026-04-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_nome_exibicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cor_footer',
            field=models.CharField(default='#212529', max_length=7),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cor_header',
            field=models.CharField(default='#2c3e50', max_length=7),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cor_nav',
            field=models.CharField(default='#34495e', max_length=7),
        ),
    ]
