# Generated by Django 6.0.4 on 2026-06-05 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_cor_footer_portfolio_cor_header_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('curso', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('git', models.URLField(blank=True)),
                ('linked', models.URLField(blank=True)),
                ('url_imagem', models.URLField(blank=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
